### ISSUE TITLE
Laravel 5.5 & 5.6 update for auto-discovery?

### ISSUE THREAD

**Issue by bridgeport** [netpeoplehu/view-composer#1]
Thanks for this nice, concise package.

1. It would be nice to see this add autodiscovery so that it doesn't have to be added to `config.php`
2. The read me has a typo: `php artisan vendor:publush --tag=config` (publush should be publish)
3. When I run the `php artisan vendor:publish --tag=config` it actually publishes `debugbar.php` (https://github.com/barryvdh/laravel-debugbar) instead
4. If `view-composers.php` isn't published, the following exception is thrown:
```
ErrorException (E_WARNING)
Invalid argument supplied for foreach()

/**
 * Register the application services.
 *
 * @return void
 */
public function register()
{
    $composers = config('view-composers');

    foreach ($composers as $composer => $views) {
        $this->app->make('view')->composer($views, $composer);
    }
}
```
Of course, if anyone is using this package, they'd need to publish the config file, but I assume you'd want the package to silently do nothing and not throw an exception if the file hasn't yet been created.

Thanks.

**Comment by torosegon** [comment]
https://github.com/netpeoplehu/view-composer/releases/tag/v1.1.0
